In [1]:
# Unsupervised_Learning
# Which is used unlabed data => means there is no target value

In [2]:
# Difference Types Of Sampling Techniques
# Different types of sampling technique
# 1)Simple random sampling
# 2)Stratified sampling
# -divide population into meaningful group called as strata then randomly 
# -select observation from each group 
# 3)Systematic sampling Technique
# - select observation at regular interval after choosing starting point randomly
# 4)Convenience Sampling 
# - A convenience sampling simply includes the individual who happen to most accessible to the researcher

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans

In [4]:
df=pd.read_csv('University_Clustering.csv')

In [5]:
df.head()

       Univ State   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0     Brown    RI  1310     89      22       13     22704        94
1   CalTech    CA  1415    100      25        6     63575        81
2       CMU    PA  1260     62      59        9     25026        72
3  Columbia    NY  1310     76      24       12     31510        88
4   Cornell    NY  1280     83      33       13     21864        90

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.drop('State',inplace=True,axis=1)

In [8]:
df.shape

(25, 7)

In [9]:
df.describe()

               SAT       Top10     Accept    SFRatio      Expenses   GradRate
count    25.000000   25.000000  25.000000  25.000000     25.000000  25.000000
mean   1264.640000   75.200000  38.160000  13.200000  26557.480000  86.840000
std     110.128289   19.161594  19.372833   4.778424  14085.585052   8.754427
min    1005.000000   28.000000  12.000000   6.000000   8704.000000  67.000000
25%    1200.000000   62.000000  24.000000  10.000000  15122.000000  81.000000
50%    1285.000000   82.000000  33.000000  12.000000  23000.000000  90.000000
75%    1340.000000   90.000000  52.000000  17.000000  32162.000000  94.000000
max    1415.000000  100.000000  90.000000  25.000000  63575.000000  98.000000

In [10]:
# df.drop('Univ',inplace=True,axis=1)
df_new=df.drop('Univ',axis=1)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
cols = ['SAT', 'Top10', 'Accept', 'SFRatio', 'Expenses', 'GradRate']

In [13]:
scaler = StandardScaler()
df[cols] = scaler.fit_transform(df[cols])

In [14]:
print(df[cols].head())

        SAT     Top10    Accept   SFRatio  Expenses  GradRate
0  0.420377  0.735041 -0.851359 -0.042718 -0.279217  0.834737
1  1.393471  1.320944 -0.693309 -1.537844  2.682235 -0.680847
2 -0.043001 -0.703083  1.097916 -0.897076 -0.110969 -1.730097
3  0.420377  0.042611 -0.745993 -0.256307  0.358852  0.135237
4  0.142350  0.415458 -0.271845 -0.042718 -0.340083  0.368403

In [15]:
print(df[cols].describe())

                SAT         Top10        Accept       SFRatio      Expenses  \
count  2.500000e+01  2.500000e+01  2.500000e+01  2.500000e+01  2.500000e+01
mean  -9.237056e-16 -1.509903e-16  1.421085e-16  1.421085e-16  3.552714e-17
std    1.020621e+00  1.020621e+00  1.020621e+00  1.020621e+00  1.020621e+00
min   -2.406230e+00 -2.514055e+00 -1.378190e+00 -1.537844e+00 -1.293637e+00
25%   -5.990552e-01 -7.030832e-01 -7.459926e-01 -6.834861e-01 -8.285980e-01
50%    1.886876e-01  3.621944e-01 -2.718447e-01 -2.563073e-01 -2.577698e-01
75%    6.984035e-01  7.883054e-01  7.291340e-01  8.116398e-01  4.060953e-01
max    1.393471e+00  1.320944e+00  2.731091e+00  2.520355e+00  2.682235e+00

           GradRate
count  2.500000e+01
mean  -3.907985e-16
std    1.020621e+00
min   -2.313014e+00
25%   -6.808469e-01
50%    3.684035e-01
75%    8.347370e-01
max    1.301071e+00

In [16]:
# K-means is an unsupervised Machine learning algorithm used for clustering
# It groups similar data points together into k distinct cluster based on their features
# The goal is to minimise the within cluster varience (i. e. keep points in the same cluster
# as close as possible to the cluster center)
# 1)Clusters:-Groups of similar data points
# Centroid:-The mean(center of a cluster).
# K:-Number of cluster
# Distance metric:-Usually Euclidean distance is used to assign points to the nearest
# cluster
# Iterative process:-Repeats until the centroid stablise