In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.cluster import KMeans

In [3]:
df=pd.read_csv("University_Clustering.csv")

In [4]:
df

,Univ,State,SAT,Top10,Accept,SFRatio,Expenses,GradRate
0,Brown,RI,1310,89,22,13,22704,94
1,CalTech,CA,1415,100,25,6,63575,81
2,CMU,PA,1260,62,59,9,25026,72
3,Columbia,NY,1310,76,24,12,31510,88
4,Cornell,NY,1280,83,33,13,21864,90
5,Dartmouth,NH,1340,89,23,10,32162,95
6,Duke,NC,1315,90,30,12,31585,95
7,Georgetown,DC,1255,74,24,12,20126,92
8,Harvard,MA,1400,91,14,11,39525,97
9,JohnsHopkins,MD,1305,75,44,7,58691,87
10,MIT,MA,1380,94,30,10,34870,91
11,Northwestern,IL,1260,85,39,11,28052,89
12,NotreDame,IN,1255,81,42,13,15122,94
13,PennState,PA,1081,38,54,18,10185,80
14,Princeton,NJ,1375,91,14,8,30220,95
15,Purdue,IN,1005,28,90,19,9066,69
16,Stanford,CA,1370,92,20,8,36450,93
17,TexasA&M,TX,1075,49,67,25,8704,67
18,UCLA,CA,1200,65,48,17,19000,84
19,UCBerkeley,CA,1285,82,35,16,21000,90
20,UniversityofFlorida,FL,1125,55,58,19,13500,78
21,UniversityofMichigan,MI,1290,84,32,15,23000,91
22,UniversityofTexas,TX,1180,60,52,18,14500,82
23,VirginiaTech,VA,1150,52,63,20,12500,79
24,Yale,CT,1395,95,12,8,41000,98

In [5]:
df.head()

       Univ State   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0     Brown    RI  1310     89      22       13     22704        94
1   CalTech    CA  1415    100      25        6     63575        81
2       CMU    PA  1260     62      59        9     25026        72
3  Columbia    NY  1310     76      24       12     31510        88
4   Cornell    NY  1280     83      33       13     21864        90

In [6]:
df.tail()

,Univ,State,SAT,Top10,Accept,SFRatio,Expenses,GradRate
20,UniversityofFlorida,FL,1125,55,58,19,13500,78
21,UniversityofMichigan,MI,1290,84,32,15,23000,91
22,UniversityofTexas,TX,1180,60,52,18,14500,82
23,VirginiaTech,VA,1150,52,63,20,12500,79
24,Yale,CT,1395,95,12,8,41000,98